networks:
  proxy:
    external: true

services:
  app:
    image: learnedmachine/speakr:0.8.6-alpha@sha256:53f7e71ef8cc0dbdd82817065b45bfa339fcce5175334cdd5c392dbb9eba7085
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    networks:
        - proxy
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/instance:/data/instance
      - ./data/exports:/data/exports
      - ./data/auto-process:/data/auto-process
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speakr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.speakr.rule=Host(`${SERVICE_SUBDOMAIN:-transcriptions}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.speakr.tls=true"
      - "traefik.http.services.speakr.loadbalancer.server.port=8899"
